services:
  app:
    command: run start:debug:local
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    restart: always
    environment:
      - COMPOSE_MENU=true
      - LOG_LEVEL=debug
    depends_on:
      - postgres
    ports:
      - '9229:9229'
      - '3000:3000'
