services:
  app:
    build:
      context: .
      target: command
    command: run test:all:local
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./coverage:/usr/app/coverage
      - ./jest:/usr/app/jest
    depends_on:
      - postgres
