services:
  app:
    command: run repl:debug:local
    container_name: 'app-repl'
    stdin_open: true
    tty: true
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5440
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
